const fs = require('fs');
const path = require('path');

const dirPath = path.join(__dirname, 'assets');
const imageFiles = fs.readdirSync(dirPath).filter(file =>
  /\.(png|jpe?g|gif|webp)$/i.test(file)
);

const jsContent = `// 🔄 This file is auto-generated by generate.js
const imageFiles = ${JSON.stringify(imageFiles, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'images.js'), jsContent);
console.log('✅ images.js 생성 완료!');